# Generated by Django 2.2.4 on 2019-08-19 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='نام خانواده')),
                ('Parrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='پدر یا مادر خانواده')),
            ],
        ),
        migrations.CreateModel(
            name='Childrens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='نام فرزند')),
                ('age', models.IntegerField(verbose_name='سن فرزند')),
                ('score', models.IntegerField(verbose_name='امتیاز فرزند')),
                ('level', models.IntegerField(verbose_name='رتبه فرزند')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.Family', verbose_name='خانواده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='اکانت فرزند')),
            ],
        ),
    ]
