# Generated by Django 2.2.4 on 2019-08-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrens',
            name='card_number',
            field=models.IntegerField(default=23, verbose_name='شماره کارت '),
            preserve_default=False,
        ),
    ]
